# Generated by Django 4.2.4 on 2023-08-03 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenPass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site", models.CharField(max_length=30)),
                ("time", models.DateField(default=django.utils.timezone.now)),
                ("password", models.CharField(max_length=300)),
            ],
        ),
    ]
